/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This model shows which values are supplied by the MDA listener script. 
 */
export interface KibicaraPlatformsEmailWebapiBodyMessage { 
    text: string;
    secret: string;
}

