name: Angular Frontend

on:
  push:
    paths:
      - "kibicara-frontend/**"
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./kibicara-frontend

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: npm i
        working-directory: ${{env.working-directory}}

      - name: Install Angular CLI
        run: npm i -g @angular/cli
        working-directory: ${{env.working-directory}}

      - name: Run Linter
        run: ng lint
        working-directory: ${{env.working-directory}}
