name: Python Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: [3.8, pypy3]
    - name: run tests
      run: |
        pip install .
        pytest
